CREATE NODE TABLE IF NOT EXISTS Package (name STRING, PRIMARY KEY (name));
CREATE NODE TABLE IF NOT EXISTS File (path STRING, name STRING, loc INT64, PRIMARY KEY (path));
CREATE NODE TABLE IF NOT EXISTS Symbol (id STRING, name STRING, kind STRING, PRIMARY KEY (id));
CREATE REL TABLE IF NOT EXISTS CONTAINS (FROM Package TO File);
CREATE REL TABLE IF NOT EXISTS DEFINES (FROM File TO Symbol);
CREATE NODE TABLE IF NOT EXISTS Peer (id STRING, endpoint STRING, is_local BOOLEAN, PRIMARY KEY (id));
CREATE REL TABLE IF NOT EXISTS CONNECTED_TO (FROM Peer TO Peer, adapter STRING, latency_ms INT64, encrypted BOOLEAN);
MERGE (p:Package {name: 'adapters'});
MERGE (p:Package {name: 'main'});
MERGE (p:Package {name: 'dht'});
MERGE (p:Package {name: 'core'});
MERGE (p:Package {name: 'ui'});
MERGE (fl:File {path: 'adapters/quic_adapter.go', name: 'quic_adapter.go', loc: 209});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/quic_adapter.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::QUICAdapter', name: 'QUICAdapter', kind: 'struct'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::QUICAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::LocalAddr', name: 'LocalAddr', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::LocalAddr'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::NewQUICAdapter', name: 'NewQUICAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::NewQUICAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::Receive', name: 'Receive', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::Receive'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::Send', name: 'Send', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::Send'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter.go'}), (s:Symbol {id: 'adapters/quic_adapter.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/quic_adapter_test.go', name: 'quic_adapter_test.go', loc: 107});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/quic_adapter_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/quic_adapter_test.go::TestQUICAdapter', name: 'TestQUICAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter_test.go'}), (s:Symbol {id: 'adapters/quic_adapter_test.go::TestQUICAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/quic_adapter_test.go::TestQUICAdapterLargePayload', name: 'TestQUICAdapterLargePayload', kind: 'func'});
MATCH (fl:File {path: 'adapters/quic_adapter_test.go'}), (s:Symbol {id: 'adapters/quic_adapter_test.go::TestQUICAdapterLargePayload'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/relay_adapter.go', name: 'relay_adapter.go', loc: 280});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/relay_adapter.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::RelayServer', name: 'RelayServer', kind: 'struct'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::RelayServer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::RelayAdapter', name: 'RelayAdapter', kind: 'struct'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::RelayAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::Addr', name: 'Addr', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::Addr'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::NewRelayAdapter', name: 'NewRelayAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::NewRelayAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::NewRelayServer', name: 'NewRelayServer', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::NewRelayServer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::Receive', name: 'Receive', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::Receive'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::Send', name: 'Send', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::Send'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/relay_adapter.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter.go'}), (s:Symbol {id: 'adapters/relay_adapter.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/relay_adapter_test.go', name: 'relay_adapter_test.go', loc: 70});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/relay_adapter_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/relay_adapter_test.go::TestRelayServerAndAdapter', name: 'TestRelayServerAndAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/relay_adapter_test.go'}), (s:Symbol {id: 'adapters/relay_adapter_test.go::TestRelayServerAndAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/stun.go', name: 'stun.go', loc: 94});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/stun.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/stun.go::DiscoverPublicEndpoint', name: 'DiscoverPublicEndpoint', kind: 'func'});
MATCH (fl:File {path: 'adapters/stun.go'}), (s:Symbol {id: 'adapters/stun.go::DiscoverPublicEndpoint'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/stun.go::GetLocalEndpoints', name: 'GetLocalEndpoints', kind: 'func'});
MATCH (fl:File {path: 'adapters/stun.go'}), (s:Symbol {id: 'adapters/stun.go::GetLocalEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/stun_test.go', name: 'stun_test.go', loc: 42});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/stun_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/stun_test.go::TestDiscoverPublicEndpoint', name: 'TestDiscoverPublicEndpoint', kind: 'func'});
MATCH (fl:File {path: 'adapters/stun_test.go'}), (s:Symbol {id: 'adapters/stun_test.go::TestDiscoverPublicEndpoint'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/stun_test.go::TestGetLocalEndpoints', name: 'TestGetLocalEndpoints', kind: 'func'});
MATCH (fl:File {path: 'adapters/stun_test.go'}), (s:Symbol {id: 'adapters/stun_test.go::TestGetLocalEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/stun_test.go::TestUDPAdapterDiscoverEndpoints', name: 'TestUDPAdapterDiscoverEndpoints', kind: 'func'});
MATCH (fl:File {path: 'adapters/stun_test.go'}), (s:Symbol {id: 'adapters/stun_test.go::TestUDPAdapterDiscoverEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/tls_helper.go', name: 'tls_helper.go', loc: 47});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/tls_helper.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/tls_helper.go::GenerateTLSConfig', name: 'GenerateTLSConfig', kind: 'func'});
MATCH (fl:File {path: 'adapters/tls_helper.go'}), (s:Symbol {id: 'adapters/tls_helper.go::GenerateTLSConfig'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/udp_adapter.go', name: 'udp_adapter.go', loc: 190});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/udp_adapter.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::UDPAdapter', name: 'UDPAdapter', kind: 'struct'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::UDPAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::DiscoverEndpoints', name: 'DiscoverEndpoints', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::DiscoverEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::Endpoints', name: 'Endpoints', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::Endpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::NewUDPAdapter', name: 'NewUDPAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::NewUDPAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::Receive', name: 'Receive', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::Receive'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::Send', name: 'Send', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::Send'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter.go'}), (s:Symbol {id: 'adapters/udp_adapter.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/udp_adapter_test.go', name: 'udp_adapter_test.go', loc: 79});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/udp_adapter_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/udp_adapter_test.go::TestUDPAdapter', name: 'TestUDPAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter_test.go'}), (s:Symbol {id: 'adapters/udp_adapter_test.go::TestUDPAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/udp_adapter_test.go::TestUDPAdapterMTU', name: 'TestUDPAdapterMTU', kind: 'func'});
MATCH (fl:File {path: 'adapters/udp_adapter_test.go'}), (s:Symbol {id: 'adapters/udp_adapter_test.go::TestUDPAdapterMTU'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/webrtc_adapter.go', name: 'webrtc_adapter.go', loc: 249});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/webrtc_adapter.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::WebRTCAdapter', name: 'WebRTCAdapter', kind: 'struct'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::WebRTCAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::AcceptAnswer', name: 'AcceptAnswer', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::AcceptAnswer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::AcceptOffer', name: 'AcceptOffer', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::AcceptOffer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::CreateDataChannel', name: 'CreateDataChannel', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::CreateDataChannel'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::CreateOffer', name: 'CreateOffer', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::CreateOffer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::NewWebRTCAdapter', name: 'NewWebRTCAdapter', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::NewWebRTCAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::Receive', name: 'Receive', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::Receive'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::Send', name: 'Send', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::Send'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter.go'}), (s:Symbol {id: 'adapters/webrtc_adapter.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'adapters/webrtc_adapter_test.go', name: 'webrtc_adapter_test.go', loc: 97});
MATCH (p:Package {name: 'adapters'}), (fl:File {path: 'adapters/webrtc_adapter_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'adapters/webrtc_adapter_test.go::TestWebRTCAdapterCommunication', name: 'TestWebRTCAdapterCommunication', kind: 'func'});
MATCH (fl:File {path: 'adapters/webrtc_adapter_test.go'}), (s:Symbol {id: 'adapters/webrtc_adapter_test.go::TestWebRTCAdapterCommunication'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'cmd/chat/main.go', name: 'main.go', loc: 168});
MATCH (p:Package {name: 'main'}), (fl:File {path: 'cmd/chat/main.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (fl:File {path: 'cmd/node/main.go', name: 'main.go', loc: 140});
MATCH (p:Package {name: 'main'}), (fl:File {path: 'cmd/node/main.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (fl:File {path: 'core/cascade.go', name: 'cascade.go', loc: 132});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/cascade.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/cascade.go::StreamChunk', name: 'StreamChunk', kind: 'struct'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::StreamChunk'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::CascadeNode', name: 'CascadeNode', kind: 'struct'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::CascadeNode'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::AddChild', name: 'AddChild', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::AddChild'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::Broadcast', name: 'Broadcast', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::Broadcast'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::ChildrenCount', name: 'ChildrenCount', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::ChildrenCount'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::NewCascadeNode', name: 'NewCascadeNode', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::NewCascadeNode'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::OnChunk', name: 'OnChunk', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::OnChunk'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade.go::SetParent', name: 'SetParent', kind: 'func'});
MATCH (fl:File {path: 'core/cascade.go'}), (s:Symbol {id: 'core/cascade.go::SetParent'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/cascade_test.go', name: 'cascade_test.go', loc: 110});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/cascade_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/cascade_test.go::TestCascadeMaxChildrenEnforcement', name: 'TestCascadeMaxChildrenEnforcement', kind: 'func'});
MATCH (fl:File {path: 'core/cascade_test.go'}), (s:Symbol {id: 'core/cascade_test.go::TestCascadeMaxChildrenEnforcement'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/cascade_test.go::TestCascadeStreamingMultiHop', name: 'TestCascadeStreamingMultiHop', kind: 'func'});
MATCH (fl:File {path: 'core/cascade_test.go'}), (s:Symbol {id: 'core/cascade_test.go::TestCascadeStreamingMultiHop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/container.go', name: 'container.go', loc: 88});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/container.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/container.go::Container', name: 'Container', kind: 'struct'});
MATCH (fl:File {path: 'core/container.go'}), (s:Symbol {id: 'core/container.go::Container'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container.go::Marshal', name: 'Marshal', kind: 'func'});
MATCH (fl:File {path: 'core/container.go'}), (s:Symbol {id: 'core/container.go::Marshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container.go::Sign', name: 'Sign', kind: 'func'});
MATCH (fl:File {path: 'core/container.go'}), (s:Symbol {id: 'core/container.go::Sign'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container.go::Unmarshal', name: 'Unmarshal', kind: 'func'});
MATCH (fl:File {path: 'core/container.go'}), (s:Symbol {id: 'core/container.go::Unmarshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container.go::Verify', name: 'Verify', kind: 'func'});
MATCH (fl:File {path: 'core/container.go'}), (s:Symbol {id: 'core/container.go::Verify'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/container_test.go', name: 'container_test.go', loc: 78});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/container_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/container_test.go::TestContainerSerialization', name: 'TestContainerSerialization', kind: 'func'});
MATCH (fl:File {path: 'core/container_test.go'}), (s:Symbol {id: 'core/container_test.go::TestContainerSerialization'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container_test.go::TestContainerSigningAndVerification', name: 'TestContainerSigningAndVerification', kind: 'func'});
MATCH (fl:File {path: 'core/container_test.go'}), (s:Symbol {id: 'core/container_test.go::TestContainerSigningAndVerification'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/container_test.go::TestGenerateIdentity', name: 'TestGenerateIdentity', kind: 'func'});
MATCH (fl:File {path: 'core/container_test.go'}), (s:Symbol {id: 'core/container_test.go::TestGenerateIdentity'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/e2ee.go', name: 'e2ee.go', loc: 132});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/e2ee.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/e2ee.go::DecryptE2EE', name: 'DecryptE2EE', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee.go'}), (s:Symbol {id: 'core/e2ee.go::DecryptE2EE'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/e2ee.go::DeriveX25519FromSeed', name: 'DeriveX25519FromSeed', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee.go'}), (s:Symbol {id: 'core/e2ee.go::DeriveX25519FromSeed'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/e2ee.go::EncryptE2EE', name: 'EncryptE2EE', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee.go'}), (s:Symbol {id: 'core/e2ee.go::EncryptE2EE'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/e2ee.go::GenerateE2EEKeyPair', name: 'GenerateE2EEKeyPair', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee.go'}), (s:Symbol {id: 'core/e2ee.go::GenerateE2EEKeyPair'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/e2ee_test.go', name: 'e2ee_test.go', loc: 69});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/e2ee_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/e2ee_test.go::TestE2EEDeriveFromSeed', name: 'TestE2EEDeriveFromSeed', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee_test.go'}), (s:Symbol {id: 'core/e2ee_test.go::TestE2EEDeriveFromSeed'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/e2ee_test.go::TestE2EEEncryptionDecryption', name: 'TestE2EEEncryptionDecryption', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee_test.go'}), (s:Symbol {id: 'core/e2ee_test.go::TestE2EEEncryptionDecryption'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/e2ee_test.go::TestE2EETamperRejection', name: 'TestE2EETamperRejection', kind: 'func'});
MATCH (fl:File {path: 'core/e2ee_test.go'}), (s:Symbol {id: 'core/e2ee_test.go::TestE2EETamperRejection'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/handshake.go', name: 'handshake.go', loc: 88});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/handshake.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/handshake.go::HandshakePayload', name: 'HandshakePayload', kind: 'struct'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::HandshakePayload'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::PingPayload', name: 'PingPayload', kind: 'struct'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::PingPayload'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::DecodeHandshake', name: 'DecodeHandshake', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::DecodeHandshake'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::DecodePing', name: 'DecodePing', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::DecodePing'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::EncodeHandshake', name: 'EncodeHandshake', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::EncodeHandshake'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::EncodePing', name: 'EncodePing', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::EncodePing'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::GenerateNonce', name: 'GenerateNonce', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::GenerateNonce'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake.go::IsFresh', name: 'IsFresh', kind: 'func'});
MATCH (fl:File {path: 'core/handshake.go'}), (s:Symbol {id: 'core/handshake.go::IsFresh'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/handshake_test.go', name: 'handshake_test.go', loc: 62});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/handshake_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/handshake_test.go::TestHandshakePayloadSerialization', name: 'TestHandshakePayloadSerialization', kind: 'func'});
MATCH (fl:File {path: 'core/handshake_test.go'}), (s:Symbol {id: 'core/handshake_test.go::TestHandshakePayloadSerialization'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/handshake_test.go::TestPingPayloadSerialization', name: 'TestPingPayloadSerialization', kind: 'func'});
MATCH (fl:File {path: 'core/handshake_test.go'}), (s:Symbol {id: 'core/handshake_test.go::TestPingPayloadSerialization'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/identity.go', name: 'identity.go', loc: 42});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/identity.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/identity.go::Ed25519Identity', name: 'Ed25519Identity', kind: 'struct'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::Ed25519Identity'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/identity.go::Bytes', name: 'Bytes', kind: 'func'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::Bytes'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/identity.go::GenerateIdentity', name: 'GenerateIdentity', kind: 'func'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::GenerateIdentity'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/identity.go::NewIdentityFromBytes', name: 'NewIdentityFromBytes', kind: 'func'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::NewIdentityFromBytes'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/identity.go::String', name: 'String', kind: 'func'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::String'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/identity.go::Verify', name: 'Verify', kind: 'func'});
MATCH (fl:File {path: 'core/identity.go'}), (s:Symbol {id: 'core/identity.go::Verify'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/interfaces.go', name: 'interfaces.go', loc: 34});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/interfaces.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/interfaces.go::Identity', name: 'Identity', kind: 'interface'});
MATCH (fl:File {path: 'core/interfaces.go'}), (s:Symbol {id: 'core/interfaces.go::Identity'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/interfaces.go::Session', name: 'Session', kind: 'interface'});
MATCH (fl:File {path: 'core/interfaces.go'}), (s:Symbol {id: 'core/interfaces.go::Session'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/interfaces.go::Adapter', name: 'Adapter', kind: 'interface'});
MATCH (fl:File {path: 'core/interfaces.go'}), (s:Symbol {id: 'core/interfaces.go::Adapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/node.go', name: 'node.go', loc: 505});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/node.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/node.go::Node', name: 'Node', kind: 'struct'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::Node'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::AddAdapter', name: 'AddAdapter', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::AddAdapter'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::AddPeer', name: 'AddPeer', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::AddPeer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::AddPeerWithLatency', name: 'AddPeerWithLatency', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::AddPeerWithLatency'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::DecryptMessage', name: 'DecryptMessage', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::DecryptMessage'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::GetPeerEndpoints', name: 'GetPeerEndpoints', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::GetPeerEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::Handshake', name: 'Handshake', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::Handshake'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::NewNode', name: 'NewNode', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::NewNode'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::OnMessage', name: 'OnMessage', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::OnMessage'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::PingPeer', name: 'PingPeer', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::PingPeer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::SendEncryptedMessage', name: 'SendEncryptedMessage', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::SendEncryptedMessage'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::SendMessage', name: 'SendMessage', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::SendMessage'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'core/node.go'}), (s:Symbol {id: 'core/node.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/node_test.go', name: 'node_test.go', loc: 90});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/node_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/node_test.go::Receive', name: 'Receive', kind: 'func'});
MATCH (fl:File {path: 'core/node_test.go'}), (s:Symbol {id: 'core/node_test.go::Receive'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node_test.go::Send', name: 'Send', kind: 'func'});
MATCH (fl:File {path: 'core/node_test.go'}), (s:Symbol {id: 'core/node_test.go::Send'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node_test.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'core/node_test.go'}), (s:Symbol {id: 'core/node_test.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node_test.go::Stop', name: 'Stop', kind: 'func'});
MATCH (fl:File {path: 'core/node_test.go'}), (s:Symbol {id: 'core/node_test.go::Stop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/node_test.go::TestNodeP2PCommunication', name: 'TestNodeP2PCommunication', kind: 'func'});
MATCH (fl:File {path: 'core/node_test.go'}), (s:Symbol {id: 'core/node_test.go::TestNodeP2PCommunication'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/smallworld.go', name: 'smallworld.go', loc: 224});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/smallworld.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/smallworld.go::PeerEntry', name: 'PeerEntry', kind: 'struct'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::PeerEntry'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::SmallWorldTable', name: 'SmallWorldTable', kind: 'struct'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::SmallWorldTable'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::AddPeer', name: 'AddPeer', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::AddPeer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::CalculateDegree', name: 'CalculateDegree', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::CalculateDegree'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::CompareDistance', name: 'CompareDistance', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::CompareDistance'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::EqualIdentities', name: 'EqualIdentities', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::EqualIdentities'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::FindClosestPeers', name: 'FindClosestPeers', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::FindClosestPeers'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::GetPeer', name: 'GetPeer', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::GetPeer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::LeadingZeroBits', name: 'LeadingZeroBits', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::LeadingZeroBits'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::NewSmallWorldTable', name: 'NewSmallWorldTable', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::NewSmallWorldTable'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::TotalPeers', name: 'TotalPeers', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::TotalPeers'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld.go::XorDistance', name: 'XorDistance', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld.go'}), (s:Symbol {id: 'core/smallworld.go::XorDistance'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'core/smallworld_test.go', name: 'smallworld_test.go', loc: 118});
MATCH (p:Package {name: 'core'}), (fl:File {path: 'core/smallworld_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldHopLimitDrop', name: 'TestSmallWorldHopLimitDrop', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld_test.go'}), (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldHopLimitDrop'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldMultiHopRelay', name: 'TestSmallWorldMultiHopRelay', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld_test.go'}), (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldMultiHopRelay'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldTableBoundedCapacity', name: 'TestSmallWorldTableBoundedCapacity', kind: 'func'});
MATCH (fl:File {path: 'core/smallworld_test.go'}), (s:Symbol {id: 'core/smallworld_test.go::TestSmallWorldTableBoundedCapacity'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'dht/dht.go', name: 'dht.go', loc: 188});
MATCH (p:Package {name: 'dht'}), (fl:File {path: 'dht/dht.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'dht/dht.go::DHTService', name: 'DHTService', kind: 'struct'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::DHTService'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::AddPeer', name: 'AddPeer', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::AddPeer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::NewDHTService', name: 'NewDHTService', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::NewDHTService'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::ProcessMessage', name: 'ProcessMessage', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::ProcessMessage'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::Publish', name: 'Publish', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::Publish'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::Resolve', name: 'Resolve', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::Resolve'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht.go::SetRemoteCaller', name: 'SetRemoteCaller', kind: 'func'});
MATCH (fl:File {path: 'dht/dht.go'}), (s:Symbol {id: 'dht/dht.go::SetRemoteCaller'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'dht/dht_test.go', name: 'dht_test.go', loc: 118});
MATCH (p:Package {name: 'dht'}), (fl:File {path: 'dht/dht_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'dht/dht_test.go::TestDHTPublishAndResolve', name: 'TestDHTPublishAndResolve', kind: 'func'});
MATCH (fl:File {path: 'dht/dht_test.go'}), (s:Symbol {id: 'dht/dht_test.go::TestDHTPublishAndResolve'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht_test.go::TestDHTRejectsForgedRecord', name: 'TestDHTRejectsForgedRecord', kind: 'func'});
MATCH (fl:File {path: 'dht/dht_test.go'}), (s:Symbol {id: 'dht/dht_test.go::TestDHTRejectsForgedRecord'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/dht_test.go::TestRecordSigningAndVerification', name: 'TestRecordSigningAndVerification', kind: 'func'});
MATCH (fl:File {path: 'dht/dht_test.go'}), (s:Symbol {id: 'dht/dht_test.go::TestRecordSigningAndVerification'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'dht/message.go', name: 'message.go', loc: 36});
MATCH (p:Package {name: 'dht'}), (fl:File {path: 'dht/message.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'dht/message.go::PeerInfo', name: 'PeerInfo', kind: 'struct'});
MATCH (fl:File {path: 'dht/message.go'}), (s:Symbol {id: 'dht/message.go::PeerInfo'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/message.go::Message', name: 'Message', kind: 'struct'});
MATCH (fl:File {path: 'dht/message.go'}), (s:Symbol {id: 'dht/message.go::Message'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/message.go::Marshal', name: 'Marshal', kind: 'func'});
MATCH (fl:File {path: 'dht/message.go'}), (s:Symbol {id: 'dht/message.go::Marshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/message.go::Unmarshal', name: 'Unmarshal', kind: 'func'});
MATCH (fl:File {path: 'dht/message.go'}), (s:Symbol {id: 'dht/message.go::Unmarshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'dht/record.go', name: 'record.go', loc: 92});
MATCH (p:Package {name: 'dht'}), (fl:File {path: 'dht/record.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'dht/record.go::Record', name: 'Record', kind: 'struct'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::Record'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/record.go::Marshal', name: 'Marshal', kind: 'func'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::Marshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/record.go::NewRecord', name: 'NewRecord', kind: 'func'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::NewRecord'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/record.go::Sign', name: 'Sign', kind: 'func'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::Sign'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/record.go::Unmarshal', name: 'Unmarshal', kind: 'func'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::Unmarshal'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'dht/record.go::Verify', name: 'Verify', kind: 'func'});
MATCH (fl:File {path: 'dht/record.go'}), (s:Symbol {id: 'dht/record.go::Verify'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'ui/kuzu.go', name: 'kuzu.go', loc: 447});
MATCH (p:Package {name: 'ui'}), (fl:File {path: 'ui/kuzu.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'ui/kuzu.go::GraphNode', name: 'GraphNode', kind: 'struct'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::GraphNode'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::GraphLink', name: 'GraphLink', kind: 'struct'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::GraphLink'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::GraphResponse', name: 'GraphResponse', kind: 'struct'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::GraphResponse'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::PeerQueryResult', name: 'PeerQueryResult', kind: 'struct'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::PeerQueryResult'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::CodeQueryResult', name: 'CodeQueryResult', kind: 'struct'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::CodeQueryResult'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::ExecuteCypher', name: 'ExecuteCypher', kind: 'func'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::ExecuteCypher'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::FindKuzuBinary', name: 'FindKuzuBinary', kind: 'func'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::FindKuzuBinary'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::FindKuzuDB', name: 'FindKuzuDB', kind: 'func'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::FindKuzuDB'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/kuzu.go::SyncPeersToKuzu', name: 'SyncPeersToKuzu', kind: 'func'});
MATCH (fl:File {path: 'ui/kuzu.go'}), (s:Symbol {id: 'ui/kuzu.go::SyncPeersToKuzu'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'ui/server.go', name: 'server.go', loc: 469});
MATCH (p:Package {name: 'ui'}), (fl:File {path: 'ui/server.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'ui/server.go::Server', name: 'Server', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::Server'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::SendMessageReq', name: 'SendMessageReq', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::SendMessageReq'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::PeerDTO', name: 'PeerDTO', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::PeerDTO'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::BroadcastStreamReq', name: 'BroadcastStreamReq', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::BroadcastStreamReq'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::StreamTelemetryFrame', name: 'StreamTelemetryFrame', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::StreamTelemetryFrame'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::PingReq', name: 'PingReq', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::PingReq'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::MeshNode', name: 'MeshNode', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::MeshNode'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::MeshLink', name: 'MeshLink', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::MeshLink'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::MeshGraphResponse', name: 'MeshGraphResponse', kind: 'struct'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::MeshGraphResponse'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::NewServer', name: 'NewServer', kind: 'func'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::NewServer'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server.go::Start', name: 'Start', kind: 'func'});
MATCH (fl:File {path: 'ui/server.go'}), (s:Symbol {id: 'ui/server.go::Start'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (fl:File {path: 'ui/server_test.go', name: 'server_test.go', loc: 107});
MATCH (p:Package {name: 'ui'}), (fl:File {path: 'ui/server_test.go'}) MERGE (p)-[:CONTAINS]->(fl);
MERGE (s:Symbol {id: 'ui/server_test.go::TestKuzuEndpoints', name: 'TestKuzuEndpoints', kind: 'func'});
MATCH (fl:File {path: 'ui/server_test.go'}), (s:Symbol {id: 'ui/server_test.go::TestKuzuEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
MERGE (s:Symbol {id: 'ui/server_test.go::TestUIEndpoints', name: 'TestUIEndpoints', kind: 'func'});
MATCH (fl:File {path: 'ui/server_test.go'}), (s:Symbol {id: 'ui/server_test.go::TestUIEndpoints'}) MERGE (fl)-[:DEFINES]->(s);
